### Makefile --- 

## Author: falk@lormoral
## Version: $Id: Makefile,v 0.0 2013/06/20 12:42:25 falk Exp $
## Keywords: 
## X-URL: 

LIA_TAGG=/home/falk/lia_tagg

test_text.tagged:
	cat ../test_text.xml| ${LIA_TAGG}/script/lia_clean  | ${LIA_TAGG}/script/lia_tagg+reacc -guess > $@


### Makefile ends here
