### Makefile --- 

## Author: falk@lormoral
## Version: $Id: Makefile,v 0.0 2013/06/20 18:54:13 falk Exp $
## Keywords: 
## X-URL: 

LG_HOME = /home/falk/lgtagger-1.1

test_text.tagged:
	${LG_HOME}/lgtagger -t -L ../test_text.xml > $@

### Makefile ends here
