### Makefile --- 

## Author: falk@lormoral
## Version: $Id: Makefile,v 0.0 2013/06/20 11:44:43 falk Exp $
## Keywords: 
## X-URL: 

test_text.tagged:
	cat ../test_text.xml | MElt -t > test_text.tagged

### Makefile ends here
