### Makefile --- 

## Author: falk@lormoral
## Version: $Id: Makefile,v 0.0 2013/06/20 11:27:30 falk Exp $
## Keywords: 
## X-URL: 

test_text.tagged:
	java -mx300m -cp '/home/falk/stanford-postagger-full-2013-04-04/stanford-postagger.jar:' edu.stanford.nlp.tagger.maxent.MaxentTagger -model /home/falk/stanford-postagger-full-2013-04-04/models/french.tagger -textFile ../test_text.xml > test_text.tagged


### Makefile ends here
