### Makefile --- 

## Author: falk@lormoral
## Version: $Id: Makefile,v 0.0 2013/06/20 11:29:01 falk Exp $
## Keywords: 
## X-URL: 

test_text.tagged: 
	perl /home/falk/tree-tagger/cmd/utf8-tokenize.perl -f -a /home/falk/tree-tagger/lib/french-abbreviations-utf8 ../test_text.xml | /home/falk/tree-tagger/bin/tree-tagger -token -lemma -sgml /home/falk/tree-tagger/lib/french-par-linux-3.2-utf8.bin 
### Makefile ends here
